language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install --prefer-source --no-interaction

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover